# Generated by Django 2.2 on 2021-04-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted_wish',
            field=models.CharField(default='no', max_length=55),
        ),
    ]
